Keep roots when cleaning
sbt/sbt pull request #2136
Opened 2015-07-30 19:22 UTC by pdalpra

2015-07-30 19:25 UTC, typesafe-tools commented
Can one of the admins verify this patch?

2015-07-30 19:36 UTC, dwijnand commented on notes/0.13.10/clean-leave-roots.markdown
> +- clean task does not delete root folders anymore, only contents [#106][106]/[#2133][2133] by [@pdalpra][pdalpra]
2136

2015-07-30 19:36 UTC, dwijnand commented on main/src/main/scala/sbt/Defaults.scala
> +        IO.delete(dirs)
why partition then delete both?

2015-07-30 19:55 UTC, pdalpra commented on main/src/main/scala/sbt/Defaults.scala
> +        IO.delete(dirs)
For an unknown reason, I thought that trying to delete an already deleted file could end up badly, but it won't.

2015-07-30 20:16 UTC, pdalpra commented
Commit amended

2015-08-04 18:20 UTC, jsuereth commented on notes/0.13.10/clean-leave-roots.markdown
> +- clean task does not delete root folders anymore, only contents [#106][106]/[#2136][2136] by [@pdalpra][pdalpra]
There may be even more ticket saround this.

ALSO, did you run a performance test at all to see what the impact is?  We may already be screwed for clean on windows, but I'm curious if this is noticeable on other platforms.

2015-08-04 18:28 UTC, pdalpra commented on notes/0.13.10/clean-leave-roots.markdown
> +- clean task does not delete root folders anymore, only contents [#106][106]/[#2136][2136] by [@pdalpra][pdalpra]
> There may be even more tickets around this.

I'll look for other tickets.

> ALSO, did you run a performance test at all to see what the impact is? We may already be screwed for clean on windows, but I'm curious if this is noticeable on other platforms.

The very basic tests I ran showed no noticeable difference, but I'll test on 'big' projects to see its impacts in the large.

2015-08-04 20:40 UTC, pdalpra commented on notes/0.13.10/clean-leave-roots.markdown
> +- clean task does not delete root folders anymore, only contents [#106][106]/[#2136][2136] by [@pdalpra][pdalpra]
Run some tests (running `test:compile` then `clean` on sbt itself) and it seems it has no noticeable impact on the performance of `clean`.
Also, I did not notice other tickets linked to that issue.

2015-08-09 13:51 UTC, jsuereth commented on notes/0.13.10/clean-leave-roots.markdown
> +- clean task does not delete root folders anymore, only contents [#106][106]/[#2136][2136] by [@pdalpra][pdalpra]
Which platform, just curious.

2015-08-09 13:54 UTC, pdalpra commented on notes/0.13.10/clean-leave-roots.markdown
> +- clean task does not delete root folders anymore, only contents [#106][106]/[#2136][2136] by [@pdalpra][pdalpra]
Mac OS X (I don't have any easy access to Windows, unfortunately).

2015-08-25 13:53 UTC, jsuereth commented
Note to self: This fix looks good, just need to check windows performance when I have my windows machine tonight.

2015-11-28 12:31 UTC, fommil commented
@jsuereth @eed3si9n @dwijnand may be of interest to you, I created a Windows XP VirtualBox image for ENSIME testing. May be of interest to you? Happy to share.

I'm also keen on creating a Windows 7 one, as that's what I have to use at work.

Of course, there is also AppVeyor which we're using to test our Windows builds of ENSIME. You could probably use it to test this one performance thing by testing the time of a compile / clean for something like akka.

2015-11-28 18:16 UTC, eed3si9n commented
@fommil I think it'll be useful.

2016-11-18 22:14 UTC, dwijnand commented
@fommil and/or @eed3si9n (and/or @jsuereth) what's a reasonable way to assert this doesn't bomb windows performance?

I want to either merge or close this.

2016-11-18 22:18 UTC, eed3si9n requested changes

2016-11-18 22:18 UTC, eed3si9n commented on main/src/main/scala/sbt/Defaults.scala
> +      clean.foreach(root => IO.delete((root.*** --- root).get))
One way to mitigate potential perf regression might be to avoid `***` here and scan only the first level of items using `*`.

2016-11-19 09:37 UTC, fommil commented
Without a windows perf test, is hard to say. One thing that could give an indicator would be to instrument every i/o call and count them. I hope the sbt 1.0 api will be nio compatible because that's the only way to improve things on windows. All the sbt apis that pass around Seq[File] are introducing areas of contention as the more efficient way to perform i/o is to have a scan thread and then a work pool.

2017-03-15 21:43 UTC, jvican commented
I think this is the root of a sbt problem I've been experiencing for a long time.
  
I'm happy to get this to the finish line. What do I have to do?

2017-04-11 18:52 UTC, eed3si9n commented
@jvican There's a perf concern on Windows - https://github.com/sbt/sbt/pull/2136/files#r88750604

2018-06-04 09:50 UTC, dwijnand commented
This will need a refresh. So let's close it for now, and re-review it if someone refreshes it.

2018-06-04 09:50 UTC, closed without merging