Workaround for inclusion of ScalaCheck classes in scala-partest-extras.jar
sbt/sbt pull request #2678
Opened 2016-07-20 10:53 UTC by milessabin

A test for this requires would require a local Scala distribution directory with the offending `lib/scala-partest-extras.jar`.

A snapshot or speedy 0.13.13 release would be super helpful.

2016-07-20 11:23 UTC, dwijnand commented
For context, see https://gitter.im/scala/contributors?at=578f245defc7f7b626ec9d22, which links to the GitHub issue in scala/scala, which links to an earlier conversation in the sbt/sbt-dev Gitter room.

2016-07-20 11:24 UTC, dwijnand commented
Personally I would prefer this to be fixed in scala/scala. But (I think) I understand the situation, so I can be convinced to accept this.

2016-09-15 12:27 UTC, dwijnand commented
@milessabin do you remember where we stand on this now?

2016-09-19 15:53 UTC, milessabin commented
Blimey, I'd completely forgotten about that!

2016-09-19 15:57 UTC, eed3si9n commented on testing/src/main/scala/sbt/TestFramework.scala
> +      val interfaceFilter = (name: String) => name.startsWith("org.scalatools.testing.") || name.startsWith("sbt.testing.") || name.startsWith("org.scalacheck.")
Would it make sense to implement the fix at the ScalaInstance layer? Adding check for `"org.scalacheck."` here feels odd.

2016-09-19 15:59 UTC, milessabin commented
I think maybe it would be best to merge this. If we don't we'll always be vulnerable to upstream changes.

2016-09-19 16:01 UTC, milessabin commented on testing/src/main/scala/sbt/TestFramework.scala
> +      val interfaceFilter = (name: String) => name.startsWith("org.scalatools.testing.") || name.startsWith("sbt.testing.") || name.startsWith("org.scalacheck.")
This is a `ClassLoader` rather than an Ivy level thing. It's ugly, but I think this _is_ the right place.

2016-09-19 16:06 UTC, eed3si9n commented on testing/src/main/scala/sbt/TestFramework.scala
> +      val interfaceFilter = (name: String) => name.startsWith("org.scalatools.testing.") || name.startsWith("sbt.testing.") || name.startsWith("org.scalacheck.")
`dual` filters `scalaInstance.loader`, but even as `scalaInstance.loader` scala-partest-extras.jar is not useful or potentially dangerous isn't it? I feel like the fix should be somewhere here - https://github.com/sbt/sbt/blob/0.13/util/classpath/src/main/scala/sbt/ScalaInstance.scala

2016-09-19 16:10 UTC, eed3si9n commented on testing/src/main/scala/sbt/TestFramework.scala
> +      val interfaceFilter = (name: String) => name.startsWith("org.scalatools.testing.") || name.startsWith("sbt.testing.") || name.startsWith("org.scalacheck.")
Isn't `allJars(scalaHome)` the problem?

2016-09-19 16:12 UTC, eed3si9n commented on testing/src/main/scala/sbt/TestFramework.scala
> +      val interfaceFilter = (name: String) => name.startsWith("org.scalatools.testing.") || name.startsWith("sbt.testing.") || name.startsWith("org.scalacheck.")
See also:

```scala
  private[this] val blacklist: Set[String] = Set("scala-actors.jar", "scalacheck.jar", "scala-partest.jar", "scala-partest-javaagent.jar", "scalap.jar", "scala-swing.jar")
```

2016-09-19 16:15 UTC, eed3si9n requested changes
`scala-partest-extras.jar` should be added to the blacklist here - https://github.com/sbt/sbt/blob/0.13/util/classpath/src/main/scala/sbt/ScalaInstance.scala#L110

2016-09-19 16:39 UTC, milessabin commented on testing/src/main/scala/sbt/TestFramework.scala
> +      val interfaceFilter = (name: String) => name.startsWith("org.scalatools.testing.") || name.startsWith("sbt.testing.") || name.startsWith("org.scalacheck.")
OK, point taken ... adding `scala-partest-extras.jar` to the blacklist seems plausible.

2016-09-27 22:08 UTC, dwijnand commented
Fixed in scala/scala https://github.com/scala/scala/pull/5414

2016-09-27 22:08 UTC, closed without merging