[sbt 1.0] server reboot
sbt/sbt pull request #2737
Opened 2016-09-13 05:24 UTC by eed3si9n

This implements the sbt server outlined in http://eed3si9n.com/sbt-server-reboot.

Pending https://github.com/sbt/util/pull/48

2016-09-14 08:07 UTC, Duhemm commented on reset.sh
> +rm -rf ~/.sbt/boot/scala-2.11.8/org.scala-sbt/sbt/1.0.0-SNAPSHOT/
I guess this was not committed on purpose?

2016-09-14 08:08 UTC, Duhemm commented
Should we migrate that to sjson-new and sbt-datatype before merging?

2016-09-14 14:02 UTC, eed3si9n commented on reset.sh
> +rm -rf ~/.sbt/boot/scala-2.11.8/org.scala-sbt/sbt/1.0.0-SNAPSHOT/
That was on purpose. We can put it in `scripts` directory or something to avoid clutter.

2016-09-14 14:03 UTC, eed3si9n commented
@Duhemm Good idea.

2016-10-26 15:52 UTC, dwijnand requested changes

2016-10-26 15:52 UTC, dwijnand commented on project/Dependencies.scala
> +  val utilVersion = "0.1.0-M14-SNAPSHOT"
0.1.0-M14 has been cut

2016-10-27 06:41 UTC, eed3si9n commented
Migrated to sbt-datatype + bumped up util

2016-10-27 06:45 UTC, eed3si9n commented
Rebasing on top of 1.0.x to resolve conflicts.

2016-10-27 06:54 UTC, dwijnand requested changes

2016-10-27 06:54 UTC, dwijnand commented on main-command/src/main/datatype/server.json
> +          "name": "command_line",
This should be commandLine

2016-10-27 06:54 UTC, dwijnand commented on main-command/src/main/datatype/server.json
> +          "name": "command_queue",
commandQueue

2016-10-27 13:32 UTC, eed3si9n commented
There was a rebase artifact in one of the commits, so I fixed that.

2016-10-27 13:32 UTC, eed3si9n commented on main-command/src/main/datatype/server.json
> +          "name": "command_line",
Done

2016-10-27 19:25 UTC, dwijnand approved these changes

2016-10-27 19:26 UTC, merged

2016-10-27 19:27 UTC, eed3si9n commented
codacy is mad, but Travis is green.