Safer template resolver
sbt/sbt pull request #2780
Opened 2016-10-13 00:08 UTC by eed3si9n

Fixes #2761

With sbt 0.13.13-RC1 rediscovered that the dependency pulled in from
Giter8 was affecting the plugins. To avoid this, this change splits up
the template resolver implementation to another module called
sbt-giter8-resolver, and it will be downloaded using Ivy into
`~/.sbt/0.13/templates/`, and then launched reflectively using Java as
the interface.

We need to wait till https://bintray.com/sbt/maven-releases/sbt-giter8-resolver get published to Maven Central.

2016-10-13 00:55 UTC, dwijnand requested changes
Few minor bits, but LGTM on paper.

Did you run this through the 3 issues we hit? Or shall I do that tomorrow?

Also, I'd love if you had time tomorrow to explain to me how you pull this off. Such impressed. Wow.

2016-10-13 00:55 UTC, dwijnand commented on main/src/main/scala/sbt/TemplateCommand.scala
> +            case t => throw t
Why the match?

2016-10-13 00:55 UTC, dwijnand commented on main/src/main/scala/sbt/TemplateCommand.scala
> +        val xs = updateUtil.update(m, templateDirectory)(_ => true) match {
instead of matching you can `.toList.flatten` here

2016-10-13 00:55 UTC, dwijnand commented on build.sbt
>      dependencyOverrides += plexusUtils
Can we remove the 2 instance of `dependencyOverrides += plexusUtils`?

2016-10-13 01:33 UTC, eed3si9n commented on build.sbt
>      dependencyOverrides += plexusUtils
Yes.

2016-10-13 01:34 UTC, eed3si9n commented on main/src/main/scala/sbt/TemplateCommand.scala
> +            case t => throw t
Remnant from the code that I copy pasted from. I should clean it up.

2016-10-13 01:40 UTC, dwijnand commented on main/src/main/scala/sbt/TemplateCommand.scala
> +    ClasspathUtilities.toLoader(classpathForInfo(info, ivyConf, globalBase, ivyScala, log), config.provider.loader)
TIL ClasspathUtilities.toLoader, pretty cool.

2016-10-13 05:11 UTC, eed3si9n commented
I just tested @pfn's scenario https://github.com/sbt/sbt/issues/2761#issuecomment-250509014 and seems to be working.

```
$ xsbt "gen-android com.foo Foo" android:ndkJavah
....
[info] Done packaging.
[success] Total time: 11 s, completed Oct 13, 2016 1:07:23 AM
```

2016-10-13 11:25 UTC, dwijnand commented on main/src/main/scala/sbt/TemplateCommand.scala
> +      method.invoke(interface, args: _*)
No I think it's correct here to catch InvocationTargetException and throw it's cause. (Sorry)

2016-10-13 22:16 UTC, eed3si9n commented on main/src/main/scala/sbt/TemplateCommand.scala
> +      method.invoke(interface, args: _*)
ok. Fixed it.

2016-10-13 22:34 UTC, dwijnand approved these changes

2016-10-13 22:34 UTC, dwijnand commented on main/src/main/scala/sbt/TemplateCommand.scala
> +      method.invoke(interface, args: _*)
Thanks.

2016-10-14 02:29 UTC, merged

2016-10-15 02:08 UTC, dwijnand commented on main/src/main/scala/sbt/TemplateCommand.scala
> +      val (s2, ivyConf) = extracted.runTask(Keys.ivyConfiguration, state)
Implemented this way causes `target/` trash when calling `new` unfortunately:

```
target
└── streams
    └── $global
        ├── ivyConfiguration
        │   └── $global
        │       └── streams
        │           └── out
        └── projectDescriptors
            └── $global
                └── streams
                    └── out
```