Automatically choose proper compiler bridge for dotty
sbt/sbt pull request #2902
Opened 2017-01-10 16:03 UTC by smarter

Before this commit, using dotty in your sbt project required to add:
```scala
  scalaCompilerBridgeSource := ("ch.epfl.lamp" % "dotty-sbt-bridge" %
    scalaVersion.value % "component").sources()
```
in your build.sbt. We might as well automatically do this, this reduces
the boilerplate for using dotty in your project to:
```scala
  scalaOrganization := "ch.epfl.lamp"
  scalaVersion := "0.1.1-SNAPSHOT"
  scalaBinaryVersion := "2.11" // dotty itself is only published as a
                               // 2.11 artefact currently
```

Note: I did not add a test for this since there is no released version of dotty yet, we could have a test that depends on a nightly build of dotty (http://central.maven.org/maven2/ch/epfl/lamp/dotty_2.11/) but I'm not sure if maven keeps old nightly builds around forever.

2017-01-10 16:09 UTC, dwijnand reviewed
I'll defer to @eed3si9n, as he understands how compiler bridges are meant to be used and customized.

2017-01-10 19:14 UTC, smarter commented
The single test failure appears to be spurious and is unrelated to this PR:
```scala
[info] Could not create file /tmp/sbt_ecf6163e/java-mixed/target/streams/$global/ivySbt/$global/streams/outjava.io.IOException: No such file or directory
```

2017-01-10 20:39 UTC, eed3si9n requested changes
I think it's generally ok, but could you add release notes in https://github.com/sbt/sbt/tree/0.13/notes/0.13.14 and clarify in there that Dotty support in sbt is an experimental feature that's controlled by EPFL, plz?

2017-01-11 14:49 UTC, smarter commented
Release notes added!

2017-01-11 14:54 UTC, eed3si9n approved these changes
Thanks!

2017-01-11 15:00 UTC, dwijnand commented
`->compile,default` here vs `->default(compile)` in #2903... which one should it be?

2017-01-11 15:05 UTC, smarter commented
Oops, that commit should not be there

2017-01-11 15:07 UTC, smarter commented
Fixed

2017-01-11 22:51 UTC, merged