[sbt 0.13] Maven version range improvement
sbt/sbt pull request #2959
Opened 2017-02-10 07:45 UTC by eed3si9n

Previously, when the dependency resolver (Ivy) encountered a Maven version range such as `[1.3.0,)` it would go out to the Internet to find the latest version. This would result to a surprising behavior where the eventual version keeps changing over time *even when there's a version of the library that satisfies the range condition*.

This changes to some Maven version ranges would be replaced with its lower bound so that when a satisfactory version is found in the dependency graph it will be used. You can disable this behavior using the JVM flag `-Dsbt.modversionrange=false`.

Fixes #2954
Ref #2291 / #2953

2017-02-10 07:46 UTC, eed3si9n commented on ivy/src/main/scala/sbt/VersionRange.scala
> +  def fromIvyToMavenVersion(revision: String): String = {
This function is migrated from MakePom.scala so we have version range related functions in the same spot.

2017-02-21 11:44 UTC, dwijnand requested changes
See my comment in #2954 (https://github.com/sbt/sbt/issues/2954#issuecomment-281319644). I'm not convinced the bug report is correct or the fix is correct. And I think it would be unwise to rush in such a change: we have no idea if it's correct or the impact it might have. If you _really_ want to get this merged, i.e. you _really_ need this for 0.13.14, I would *strongly* suggest you put this behind an opt-in flag, rather than behind an opt-out flag.

2017-03-06 15:42 UTC, dwijnand approved these changes
@eed3si9n is convinced this is the correct change.

We'll release a release candidate or milestone of 0.13.14, and hopefully that'll catch any regressions due to this.

2017-03-06 15:42 UTC, merged

2017-08-07 21:23 UTC, daddykotex commented
We just stumbled on this! We had issues resolving internal packages (hosted on a private artifactory).

Our projects extensively use version ranges. that means our `build.sbt` use version like `[1.0.0,)` for almost all of our internal dependencies. This is useful as it makes sure the latest version available for the dependency is resolved from the internal repository and that we don't have to update every single project and change the version. In our case, we want to resolve the latest available (from the internal repository) and not the latest in the graph.

This of course mean that we can't easily reproduce our builds.

The opt-out flag works as intended though.

By the way it was just to let you know, because I don't think you can do anything for us. We probably have an out of the norm approach. 

Thanks for your hard work on `sbt`.

2017-08-07 21:26 UTC, eed3si9n commented
> The opt-out flag works as intended though.

Good to know :) Thanks for the note.