[sbt 1.0] Make
sbt/sbt pull request #3098
Opened 2017-04-12 22:36 UTC by eed3si9n

(See the guidelines for contributing, linked above)

2017-04-13 08:41 UTC, dwijnand requested changes
Let's find some time to talk about this together (perhaps later tonight) because I have the following concerns about making the server default:

* the recent addition about "keeping the shell warm" messaging as well as its implementation
* if perhaps we want to now fold the "server" command into shell, with possibly a "old-shell" fallback command..
* (minor) the fact that sbt-extras invokes sbt explicitly with "shell" while sbt-launcher-package doesn't

I'm happy to sign-off on your Future[Unit] change if you want to tear that out of here into a new PR.

2017-04-13 20:01 UTC, eed3si9n commented
> I'm happy to sign-off on your Future[Unit] change if you want to tear that out of here into a new PR.

ok. That's split out. https://github.com/sbt/sbt/pull/3104

2017-04-14 20:37 UTC, eed3si9n commented
After discussion with @dwijnand, the server command is now called `shell`, and the old shell command is called `oldshell` - 86342d0bdd78cc18ee280610742e46a1d434295c

2017-04-14 20:53 UTC, dwijnand requested changes

2017-04-14 20:53 UTC, dwijnand commented on main/src/main/scala/sbt/Main.scala
> +    if (isInteractive && !hasCommand(state, Shell) && !hasCommand(state, OldShell) && !endsWithBoot(state)) {
This should be Shell

2017-04-14 20:54 UTC, eed3si9n commented on main/src/main/scala/sbt/Main.scala
> +    if (isInteractive && !hasCommand(state, Shell) && !hasCommand(state, OldShell) && !endsWithBoot(state)) {
It has both Shell and OldShell in the if predicate.

2017-04-14 20:55 UTC, dwijnand approved these changes

2017-04-14 20:55 UTC, dwijnand commented on main/src/main/scala/sbt/Main.scala
> +    if (isInteractive && !hasCommand(state, Shell) && !hasCommand(state, OldShell) && !endsWithBoot(state)) {
Ah it also has Shell. @eed3si9n if possible could you draw attention to these details when forward-porting?

2017-04-14 20:56 UTC, eed3si9n commented on main/src/main/scala/sbt/Main.scala
> +    if (isInteractive && !hasCommand(state, Shell) && !hasCommand(state, OldShell) && !endsWithBoot(state)) {
There's nothing to forward port since it's sbt 1.0 :)

2017-04-14 20:57 UTC, eed3si9n commented on main/src/main/scala/sbt/Main.scala
> +    if (isInteractive && !hasCommand(state, Shell) && !hasCommand(state, OldShell) && !endsWithBoot(state)) {
Oh you mean when I changed it from the 0.13?

2017-04-14 20:59 UTC, dwijnand commented on main/src/main/scala/sbt/Main.scala
> +    if (isInteractive && !hasCommand(state, Shell) && !hasCommand(state, OldShell) && !endsWithBoot(state)) {
I should've noticed the trailing commits in https://github.com/sbt/sbt/pull/3077

2017-04-14 21:34 UTC, merged