Fix implementation of `LoadBuildConfiguration`
sbt/sbt pull request #3121
Opened 2017-04-19 06:39 UTC by jvican

It mainly does three things:

* Clean up the implementation, removing unused values like
  `globalPluginDefs`.
* Make the implementation more readable.
* And the big one: Remove the creation of a classloader that we were
  instantiating but whose value we were throwing away. This has an impact
  in performance, but I'm yet to benchmark how much it is.

2017-04-19 07:54 UTC, jvican commented
I have repurposed this PR to improve `Load.scala`, which is one of my incipient work to try to improve plugin classloading.

2017-04-19 15:02 UTC, eed3si9n requested changes
Style comment.

2017-04-19 15:02 UTC, eed3si9n commented on main/src/main/scala/sbt/internal/Load.scala
> +      }.getOrElse(PluginData(globalPluginClasspath))
I generally write out pattern matching for `Option`. It's the fastest ("Not only is it by far the fastest (probably at least 10 times as fast as the alternatives), it is also the clearest." according to [Odersky](https://www.reddit.com/r/scala/comments/449td4/fold_or_pattern_matching_with_an_option/))

2017-04-19 15:02 UTC, eed3si9n commented on main/src/main/scala/sbt/internal/Load.scala
> +    val baseDir = globalPlugin.map(_.base).getOrElse(stagingDirectory)
Same here.

2017-04-21 07:10 UTC, eed3si9n commented
closing this in favor of https://github.com/sbt/sbt/pull/3130

2017-04-21 07:10 UTC, closed without merging