[sbt 1.0] Reformat using Scalafmt
sbt/sbt pull request #3125
Opened 2017-04-19 20:54 UTC by eed3si9n

Fixes #2944

Taking recommendation by @olafurpg in #3003:

> - maxColumn 100 is totally fine.
> - don't use vertical alignment, it's distracting.
> - use default or I'm happy to discuss adding style=sbt, sbt is a large enough project to merit its own style.

The two tweaking I took from original @dwijnand PRs with my added comments:

```yaml
# http://docs.scala-lang.org/style/scaladoc.html recommends the JavaDoc style.
# scala/scala is written that way too https://github.com/scala/scala/blob/v2.12.2/src/library/scala/Predef.scala
docstrings = JavaDoc

# This also seems more idiomatic to include whitespace in import x.{ yyy }
spaces.inImportCurlyBraces = true
```

2017-04-19 20:57 UTC, smarter commented on main-actions/src/main/scala/sbt/ForkTests.scala
> +                           .mkString(" ") + " failed with exit code " + ec -> SuiteResult.Error),
This is a pretty weird formatting.

2017-04-19 20:58 UTC, jvican commented
Can we please merge this after my PR is merged? Rebasing it on top of this will be very difficult and I prefer to spend that time on other things.

2017-04-19 20:59 UTC, smarter commented on main-actions/src/main/scala/sbt/Sync.scala
> +      {
This is also weird, you want `else if (...) {` on a single line, not indenting the block as if it was a normal expression.

2017-04-19 21:03 UTC, smarter commented on main-actions/src/test/scala/sbt/compiler/EvalTest.scala
> +        i)
Also unlike any kind of style a human would write.

2017-04-19 21:04 UTC, smarter commented
@olafurpg Does scalafmt take operator precedence into account when deciding where to put newlines?

2017-04-19 21:22 UTC, eed3si9n commented on main-actions/src/main/scala/sbt/Package.scala
> +        case ManifestAttributes(attributes @ _ *) => main.asScala ++= attributes
Changing `_*` to `_ *` looks odd.  

SLS says "The last pattern in a pattern sequence may be a sequence wildcard _*." - https://www.scala-lang.org/files/archive/spec/2.12/08-pattern-matching.html#pattern-sequences

2017-04-19 21:24 UTC, tpolecat commented
The lack of blank lines between definitions is among my top complaints and this doesn't seem to affect it. See [Eval.scala](https://github.com/eed3si9n/sbt/blob/499bba8142a988ffec713bd9db0db1c117c97dd7/main-actions/src/main/scala/sbt/compiler/Eval.scala) for example. Is there an easy way to improve that?

Otherwise the formatting isn't really my taste but it's consistent and it's an improvement so 👍 from me. I'm kind of ambivalent about enforcing it as part of the build vs. just doing it once and calling it good. No strong opinion.

2017-04-19 21:40 UTC, dwijnand requested changes
Thank you for the PR, @eed3si9n. Looks generally good, I've left a few comments to discuss.

2017-04-19 21:40 UTC, dwijnand commented on main-command/src/main/scala/sbt/State.scala
> +
holy shit when did scalafmt start doing this newline inserting? <3 @olafurpg

2017-04-19 21:40 UTC, dwijnand commented on main-settings/src/main/scala/sbt/Structure.scala
> +    "0.13.13"
jesus christ. We should exclude this section and the same one above. They're exceptions.

2017-04-19 21:40 UTC, dwijnand commented on main/src/main/scala/sbt/Keys.scala
> +                            "The amount of logging sent to a file for persistence.",
uh... do we want to change this like this? I know the former is longer than 100 columns, but I thinks it's about 1000x more readable. We should exclude these blocks, maybe the whole file.

2017-04-19 21:40 UTC, dwijnand commented on main/src/main/scala/sbt/Main.scala
> +      loadProject,
these binpacked would be much nicer..

2017-04-19 21:40 UTC, dwijnand commented on .scalafmt.conf
> +project.excludeFilters = [ /sbt-test/, /input_sources/ ]
we should exclude `/contraband-scala/` too otherwise scalafmt and contraband are going to keep fighting each other

2017-04-19 21:40 UTC, dwijnand commented on main-actions/src/main/scala/sbt/Package.scala
> +        case ManifestAttributes(attributes @ _ *) => main.asScala ++= attributes
It's why I'd set `spaces.beforeSeqWildcard = true`. I've no idea why the default is false. scalameta/scalafmt#772

2017-04-19 21:40 UTC, dwijnand commented on main-actions/src/main/scala/sbt/Package.scala
> +        case MainClass(mainClassName) => main.put(Attributes.Name.MAIN_CLASS, mainClassName)
Can we at least agree that `=>`s should be aligned? I find the former state to be so much more legible..

2017-04-19 21:40 UTC, dwijnand commented on project/Formatting.scala
> -        if (diff.nonEmpty) sys.error("Working directory is dirty!\n" + diff)
We should continue to enforce the format with CI.

2017-04-19 21:47 UTC, eed3si9n commented on main/src/main/scala/sbt/Keys.scala
> +                            "The amount of logging sent to a file for persistence.",
Maybe we need a Perl script to lift the key description such as `"The amount of logging sent to a file for persistence."` into a variable name right above the `val`.

2017-04-20 00:02 UTC, eed3si9n commented on main-actions/src/main/scala/sbt/Package.scala
> +        case MainClass(mainClassName) => main.put(Attributes.Name.MAIN_CLASS, mainClassName)
Sure why not.

2017-04-20 00:38 UTC, dwijnand approved these changes

2017-04-20 00:38 UTC, dwijnand commented on main-settings/src/main/scala/sbt/Structure.scala
>    // this is the least painful arrangement I came up with
The way to exclude this block is by surrounding it with

```
// format: off
```

and then

```
// format: on
```

same for the t2ToApp2, etc block below.

I can do it in a follow up PR if you'd prefer.

2017-04-20 08:33 UTC, olafurpg commented on main-actions/src/main/scala/sbt/ForkTests.scala
> +                           .mkString(" ") + " failed with exit code " + ec -> SuiteResult.Error),
Yes, I agree. Scalafmt leaves respects line breaks around infix operators. If you put a newline between `+` and `options` the formatting would look nicer.

2017-04-20 08:36 UTC, olafurpg commented on main-actions/src/test/scala/sbt/compiler/EvalTest.scala
> +        i)
This is a known issue https://github.com/scalameta/scalafmt/issues/667 I suspect it would look nicer wrapped in curly braces.

2017-04-20 08:37 UTC, olafurpg commented on main-command/src/main/scala/sbt/State.scala
> +
Scalafmt inserts a blank line if there's a docstring :))

2017-04-20 08:43 UTC, olafurpg commented on main-actions/src/main/scala/sbt/Package.scala
> +        case ManifestAttributes(attributes @ _ *) => main.asScala ++= attributes
I've opened https://github.com/scalameta/scalafmt/issues/890

2017-04-20 08:45 UTC, olafurpg commented
@tpolecat There is a `newlines.alwaysBeforeTopLevelStatements` setting http://scalameta.org/scalafmt/#newlines.alwaysBeforeTopLevelStatements which was contributed by @Daxten to enforce blank lines between definitions. Currently, scalafmt only enforces a blank before docstrings.

2017-04-20 08:51 UTC, olafurpg commented on main-actions/src/main/scala/sbt/Package.scala
> +        case MainClass(mainClassName) => main.put(Attributes.Name.MAIN_CLASS, mainClassName)
FWIW, the Scala.js coding style permits vertical alignment in pattern matching only.

You can limit vertical alignment to `=>` in pattern matching only with 

```
align.tokens = [{owner="Case", code="=>"}]
```

That will avoid unwanted alignment for lambda arrows, import rename arrows etc.

2017-04-20 08:57 UTC, olafurpg commented on main-actions/src/test/scala/sbt/compiler/EvalTest.scala
> +        i)
Wrapping it in curly braces and inserting a newline after `==` yields this output

```scala
  private[this] def testImport(imports: Seq[String]): Int => Prop = { i =>
    value(eval.eval("abs(" + i + ")", new EvalImports(imports.zipWithIndex, "imp"))) ==
      math.abs(i)
  }
```

I tried really hard to come up with a better solution for infix operators but it always came out badly in some weird DSLs in the wild. Until scalafmt is able to handle infix operators well in all cases I thought it was best to leave those line break choices to the user.

2017-04-20 09:25 UTC, olafurpg commented
First of all, I'm really happy to see this PR 😄 A few notes

- scalafmt does not insert or remove line breaks around infix operators, so weird formatting like below can usually be fixed with a bit of manual help

```scala
foo(aaaaaa(bbbbbbbbbbbbbbbb), 333333333333) == a(
  2)
// manually insert newline after `==`
foo(aaaaaa(bbbbbbbbbbbbbbbb), 333333333333) ==
  a(2)
```
I really wanted scalafmt to be able handle infix operators well (at least common ones like == && ||) but I always hit on places where I didn't like the output. Instead of forcing bad formatted output without an escape hatch, scalafmt respects the line break choices in the original source for infix operators.

- if you enforce scalafmt in CI with `scalafmt --test`, you can customize the failure message with to help contributors figure out how to fix the problem.

```scala
onTestFailure = "To fix this error, run XXX".
```

- if you really dislike the output, please report an issue with the original code, formatted code and your expected output. Some things are super easy to fix while others are a lot harder. 

- the `docstring`/`spaces.inImportCurlyBraces`/`spaces.beforeSeqWildcard` options are totally reasonable. I've opened https://github.com/scalameta/scalafmt/issues/890 to discuss enabling those in the default style. If that meets big resistance, I'm open to add `style=sbt`.

Finally, my experience is that the formatted output tends to look a bit nicer when new code is written with scalafmt in mind (esp. max column) compared to when an existing codebase is formatted with scalafmt.

2017-04-20 10:49 UTC, dwijnand commented
@tpolecat @olafurpg I too find spaces between multi-line definitions to make code much better. The reason I didn't include `newlines.alwaysBeforeTopLevelStatements=true` was because of issues in how that works. I've taken the time to file those issues now (https://github.com/scalameta/scalafmt/issues/892, https://github.com/scalameta/scalafmt/issues/893), then we can do that formatting.

2017-04-20 11:14 UTC, Daxten commented
Will take a look this weekend!

2017-04-21 16:05 UTC, merged

2017-04-21 16:38 UTC, SethTisue commented
scalafmt all the things! 🎉

2017-06-16 18:52 UTC, eed3si9n commented on project/AutomateScalafmtPlugin.scala
> +  override def requires = ScalafmtPlugin
@dwijnand See here. It requires ScalafmtPlugin.