Fix default scalaBinaryVersion for Dotty
sbt/sbt pull request #3152
Opened 2017-04-28 09:46 UTC by smarter

Dotty is versioned as 0.*, but `CrossVersionUtil#binaryScalaVersion`
will return the full version instead of just major.minor for all
compiler versions < 2.10, add a special case for Dotty to avoid this.

2017-04-28 09:58 UTC, dwijnand requested changes

2017-04-28 09:58 UTC, dwijnand commented on util/cross/src/main/input_sources/CrossVersionUtil.scala
> +			if (full.startsWith("0."))
This is.. unfortunate.

2017-04-28 09:58 UTC, dwijnand approved these changes

2017-04-28 09:59 UTC, dwijnand commented
oops, miss clicked "request changes".

2017-04-28 11:41 UTC, eed3si9n approved these changes

2017-04-29 10:56 UTC, smarter commented
Another spurious test failure, unrelated to the PR:
```scala
[info] [error] (*:ivyConfiguration) Could not create file /tmp/sbt_3d9e72fd/info/target/streams/$global/ivyConfiguration/$global/streams/outjava.io.IOException: No such file or directory

[info] [error] Total time: 0 s, completed Apr 28, 2017 1:05:03 PM

[error] x dependency-management / info

[error]    {line 4}  Command failed: clean failed
```

2017-05-03 15:49 UTC, merged