Remove implicit formats from Defaults
sbt/sbt pull request #3173
Opened 2017-05-05 19:13 UTC by jvican

`Defaults` is not the right place to expose the implicit formats. Since
this file is usually read by people, we should keep it as clean as
possible and hide implementation details.

This commit does a small cleanup in update too:

* Uses `dependsOn` to show idiomatic ways of expressing our previous
  implementation.
* Hides the JsonKeyFormat in an `UnsafeLibraryManagementCodec` file.
  I must admit that I don't know why we have an extra format for
  ModuleID.

Regarding dependency positions, the meat of the implementation has been
moved to an independent file, as well as the implicit formats. The
implementation of `dependencyPositionsTask` is now kept to a bare
minimum. Docs have been added too.

2017-05-10 20:55 UTC, eed3si9n requested changes

2017-05-10 20:55 UTC, eed3si9n commented on main/src/main/scala/sbt/internal/librarymanagement/UnsafeLibraryManagementCodec.scala
> +package sbt.internal.librarymanagement
This should be moved to sbt.internal.

2017-05-10 22:43 UTC, jvican commented on main/src/main/scala/sbt/internal/librarymanagement/UnsafeLibraryManagementCodec.scala
> +package sbt.internal.librarymanagement
I didn't quite get the reasonind behind this. To me, this utility is totally part of `librarymanagement` and should go here. The rest of the utilities in this package are very similar to this one. Can you elaborate?

2017-05-10 22:45 UTC, eed3si9n commented on main/src/main/scala/sbt/internal/librarymanagement/UnsafeLibraryManagementCodec.scala
> +package sbt.internal.librarymanagement
For the sake of code organization, sbt/sbt code should be packaged under `sbt.internal`. If it belongs to `sbt.internal.librarymanagement` it should move to sbt/lm.

2018-06-04 09:54 UTC, dwijnand commented
This conflicts with current 1.x Defaults.scala. Probably easier to re-author the change than attempt to rebase it. Closing, new PR welcome.

2018-06-04 09:54 UTC, closed without merging