Fix sbt/sbt#3143: Add test to confirm leak is gone
sbt/sbt pull request #3238
Opened 2017-06-01 21:40 UTC by jvican

The following commit adds the test case used to report #3143 in a big
projects with lots of cross versions and modules. The execution of the
test is instant!

2017-06-02 06:58 UTC, dwijnand approved these changes

2017-06-03 07:07 UTC, eed3si9n requested changes

2017-06-03 07:07 UTC, eed3si9n commented on main/src/main/scala/sbt/Cross.scala
> -  private trait ScalaVersion {
Could we test without change to `main/src`?
Also formatting is failing.

2018-03-07 23:17 UTC, eed3si9n commented
Merged as https://github.com/sbt/sbt/pull/3998

2018-03-07 23:17 UTC, closed without merging