Move the tuple enrichments into sbt.Scoped.syntax
sbt/sbt pull request #3291
Opened 2017-06-26 13:08 UTC by dwijnand

This undeprecates the syntax, but at the same times moves it out of
implicit scope, therefore requiring a 'import Scoped.syntax._' to opt-in to
the old syntax.

Fixes #2762

2017-06-26 19:19 UTC, eed3si9n requested changes
I am fine with the overall direction, but I don't think the name `Scoped.syntax` is quite right, since `Scoped` just happens to be a common trait between setting keys etc, and has nothing to do with tuple DSL. The old implementation is there more for implicit scope reason.

2017-06-26 19:19 UTC, eed3si9n commented on main-settings/src/main/scala/sbt/Structure.scala
> +  object syntax {
If we are making this optional, I think the proper way of doing it is to turn it into a trait called `TupleSyntax`, and then define an auto plugin that introduces `TupleSyntax` as part of `autoImport`. See `trait SlashSyntax` here - https://github.com/sbt/sbt-slash/blob/b852a828bf266226a63b569c6fa9ec6178846090/src/main/scala/sbt/sbtslash/SlashSyntax.scala

2017-06-26 22:28 UTC, jvican requested changes
I agree with Eugene here, the naming is my only complaint. Thanks for the work on this.

2017-06-27 07:57 UTC, dwijnand commented on main-settings/src/main/scala/sbt/Structure.scala
> +  object syntax {
Can't use autoImport because autoImport is always imported even if the plugin isn't enabled, which is #1449.

2017-06-27 19:17 UTC, eed3si9n approved these changes

2017-06-27 19:17 UTC, merged

2017-06-28 02:40 UTC, eed3si9n commented on main-settings/src/main/scala/sbt/Structure.scala
> +  object syntax {
I just noticed this comment. We just need to make it another jar like scripted, I think.