Add, configure & enable MiMa
sbt/sbt pull request #3349
Opened 2017-07-20 16:31 UTC by dwijnand

2017-07-20 20:20 UTC, eed3si9n requested changes

2017-07-20 20:20 UTC, eed3si9n commented on build.sbt
> +    mimaSettings,
```
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-sbt#sbt-launch_2.12;1.0.0-RC2: not found
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-sbt#test-agent_2.12;1.0.0-RC2: not found
[error] sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-sbt#sbt_2.12;1.0.0-RC2: not found
[error] (bundledLauncherProj/*:mimaPreviousClassfiles) sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-sbt#sbt-launch_2.12;1.0.0-RC2: not found
[error] (testAgentProj/*:mimaPreviousClassfiles) sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-sbt#test-agent_2.12;1.0.0-RC2: not found
[error] (sbtProj/*:mimaPreviousClassfiles) sbt.librarymanagement.ResolveException: unresolved dependency: org.scala-sbt#sbt_2.12;1.0.0-RC2: not found
```

Similar to util-interface, these are not cross published artifacts.

2017-07-26 14:20 UTC, dwijnand commented
Yay! All green.

2017-07-26 14:20 UTC, eed3si9n approved these changes
LGTM

2017-07-26 14:20 UTC, merged