Move sbt.protocol to sbt.internal.protocol
sbt/sbt pull request #3366
Opened 2017-07-25 04:53 UTC by eed3si9n

Fixes sbt/sbt#3327

2017-07-25 06:31 UTC, eed3si9n commented
I initially pushed to sbt/sbt, and cancelled it so I got the failure. On my own branch travis/push passed fine - https://travis-ci.org/eed3si9n/sbt/builds/257165587

2017-07-25 06:36 UTC, dwijnand approved these changes

2017-07-25 06:37 UTC, dwijnand requested changes
Actually, let me bump MiMa, just so we can double-check the effects of this change.

2017-07-26 13:51 UTC, dwijnand commented
I don't know what I was thinking MiMa could do for us - it's not going to do usage level analysis..

So I did a little myself, and I think this change breaks our public binary API. The example I found is from the first object in the first file: `ForkTests`. It returns the test output, and nested in it is a contraband-created TestResult. By changing the package name we're removing classes that are part of the public API.

2017-07-26 13:51 UTC, closed without merging