Fix run's support of directories in the classpath
sbt/sbt pull request #3517
Opened 2017-09-12 13:36 UTC by dwijnand

Fixes #3504

2017-09-12 15:52 UTC, eed3si9n requested changes
Looks good overall.

Could we add a scripted test to test your new directory change detection in https://github.com/sbt/sbt/tree/1.0.x/sbt/src/sbt-test/run or piggy back on an existing test?

2017-09-12 16:19 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=pull/3517/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

2017-09-12 16:22 UTC, eed3si9n approved these changes

2017-09-13 09:21 UTC, typesafe-tools commented
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=pull/3517/head&deploy_to_bintray=false&run_sbt_community=false">this link.</A>

2017-09-13 15:07 UTC, merged