Resolve various warnings
sbt/sbt pull request #3648
Opened 2017-10-19 01:10 UTC by sschaef

This resolves various warnings that occur during compilation. Included:

- Some entries are added to gitignore 
- Some warnings about unused code have been disabled because the warnings can't be resolved (warnings in contraband generated code, warnings in unused parameter in abstract definitions etc.)
- Not all warnings about unused pattern vars are resolved because there are simply too many of them and I lost interest in resolving the remaining ones. In order to get rid of the warnings I disabled them completely because unused pattern vars are not a problem anyway.
- No semantic changes should be introduced by this PR, otherwise it is an oversight.

2017-10-19 02:50 UTC, eed3si9n requested changes
Thank you so much!
Minor comment on gitignore, but overall LGTM.

2017-10-19 02:50 UTC, eed3si9n commented on .gitignore
> +bin/
Tool specific rules should go into global gitignore https://help.github.com/articles/ignoring-files/

2017-10-19 02:50 UTC, eed3si9n commented on project/Util.scala
> +          "-Ywarn-unused:-params,-implicits,_",
👍

2017-10-19 11:10 UTC, sschaef commented
I removed the commit with the updated `.gitignore` file. The failing tests are they related to my changes or is this some other issue?

2017-10-20 04:52 UTC, eed3si9n commented
@sschaef The Travis CI failure is likely legitimate.

```
[error] x project / unified 
[error]  Cause of test exception: {line 28}  Command failed: inspectCheck failed
[info] [error] java.lang.RuntimeException: actual:
[info] [error] Task: Unit
[info] [error] Description:
[info] [error] 	Executes all tests.
[info] [error] Provided by:
[info] [error] 	ProjectRef(uri("file:/tmp/sbt_e0e362e7/"), "root") / Test / test
[info] [error] Defined at:
[info] [error] 	(sbt.Defaults.testTasks) Defaults.scala:673
[info] [error] Dependencies:
[info] [error] 	Test / executeTests
[info] [error] 	Test / test / streams
[info] [error] 	Test / state
[info] [error] 	Test / test / testResultLogger
[info] [error] Delegates:
[info] [error] 	Test / test
[info] [error] 	Runtime / test
[info] [error] 	Compile / test
[info] [error] 	test
[info] [error] 	ThisBuild Test / test
[info] [error] 	ThisBuild Runtime / test
[info] [error] 	ThisBuild Compile / test
[info] [error] 	ThisBuild test
[info] [error] 	Zero / Test / test
[info] [error] 	Zero / Runtime / test
[info] [error] 	Zero / Compile / test
[info] [error] 	Global / test
[info] [error] Related:
[info] [error] 	projA Test / test
[info] [error] 
[info] [error] 
[info] [error] expected:
[info] [error] Task: Unit
[info] [error] Description:
[info] [error] 	Executes all tests.
[info] [error] Provided by:
[info] [error] 	ProjectRef(uri("file:/tmp/sbt_e0e362e7/"), "root") / Test / test
[info] [error] Defined at:
[info] [error] 	(sbt.Defaults.testTasks) Defaults.scala:670
[info] [error] Dependencies:
[info] [error] 	Test / executeTests
[info] [error] 	Test / test / streams
[info] [error] 	Test / state
[info] [error] 	Test / test / testResultLogger
[info] [error] Delegates:
[info] [error] 	Test / test
[info] [error] 	Runtime / test
[info] [error] 	Compile / test
[info] [error] 	test
[info] [error] 	ThisBuild / Test / test
[info] [error] 	ThisBuild / Runtime / test
[info] [error] 	ThisBuild / Compile / test
[info] [error] 	ThisBuild / test
[info] [error] 	Zero / Test / test
[info] [error] 	Zero / Runtime / test
[info] [error] 	Zero / Compile / test
[info] [error] 	Global / test
[info] [error] Related:
[info] [error] 	projA / Test / test
[info] [error] 
[info] [error] diff:
[info] [error] Vector((ThisBuild Test / test,ThisBuild / Test / test), (ThisBuild Runtime / test,ThisBuild / Runtime / test), (ThisBuild Compile / test,ThisBuild / Compile / test), (ThisBuild test,ThisBuild / test), (projA Test / test,projA / Test / test))
```

When I run `scripted project/unified` on 1.x branch it succeeds.

2017-10-20 04:55 UTC, eed3si9n requested changes

2017-10-20 04:55 UTC, eed3si9n commented on main-settings/src/main/scala/sbt/Def.scala
> +          ref => displayRelativeReference(current, ref)
This is wrong because it'll put `false`.

2017-10-21 01:47 UTC, eed3si9n commented
Closing this in favor of #3658

2017-10-21 01:47 UTC, closed without merging