Enable parallel execution of scripted in the plugin
sbt/sbt pull request #3657
Opened 2017-10-20 22:55 UTC by jvican

The change to enable batched and parallel execution for scripted was
done only for the scripted-sbt project. This pull request enables it for
scripted-plugin, so that all sbt plugins in 1.x. can benefit from it.

By default, it configures a number of parallel instances of 1 (though
batch execution is enabled by default). Users can change the number of
parallel sbt hosts running scripted tests via the
`scriptedParallelInstances` setting.

2017-10-21 08:55 UTC, jvican commented
To be sure this does not cause any problem in the future, I have tested that scripted runs correctly with both batch execution enabled and disabled in `sbt-native-packager`.

2017-10-24 11:24 UTC, jvican commented
@eed3si9n Can you please review this?

2017-10-25 03:53 UTC, eed3si9n requested changes
Overall LGTM, but I think this should target 1.x branch since it's a feature addition.

2017-10-25 21:17 UTC, dwijnand commented on scripted/plugin/src/main/scala/sbt/ScriptedPlugin.scala
> +  private[this] val iCls = classOf[Integer]
Any particular reason these aren't defined inside `scriptedRunTask`?

IIUC there's no computation done for these; they're just class literals.

2017-10-25 21:18 UTC, dwijnand commented on scripted/sbt/src/main/scala/sbt/test/ScriptedTests.scala
> +      instances: Integer
Why Integer and not Int?

2017-10-25 21:22 UTC, dwijnand approved these changes
LGTM. Just a couple of minor questions.

2018-01-17 14:24 UTC, dwijnand commented
Rebased in #3891.

2018-01-17 14:24 UTC, closed without merging