IPC Unix domain socket / Windows named pipe
sbt/sbt pull request #3742
Opened 2017-11-15 09:05 UTC by eed3si9n

In addition to TCP, this adds support for IPC (interprocess communication) using Unix domain socket and Windows named pipe. The Java socket implementation for IPC is lifted from facebook/nailgun, which is released under Apache v2.

The use of Unix domain socket has performance and security benefits.

Here's screenshot of this running on a Windows virtual machine:
![windows_7_64bit__running_](https://user-images.githubusercontent.com/184683/32827235-74fd2880-c9b9-11e7-830b-2617f4beb322.png)

### serverConnectionType

This introduces a new setting key called `serverConnectionType`, which is set to `ConnectionType.Local` by default:

```scala
serverConnectionType := ConnectionType.Local,
```

The other option is `ConnectionType.Tcp`.

### active.json

To communicate to the clients about the connection type, it uses URI with `local:` as the protocol.

```
{"uri":"local:///Users/xxx/.sbt/1.0/server/0845deda85cb41abdb9f/sock"}
```

2017-11-15 21:19 UTC, eed3si9n commented
Travis passed the test. Codacy problems are coming from the Nailgun code's variable names.

2017-11-17 18:00 UTC, dwijnand commented
Why does this include a bunch of Nailgun source code?

2017-11-20 02:25 UTC, eed3si9n commented
@dwijnand The only available nailgun artifact on Maven Central is 0.9.1, and the code that I am borrowing from them is fairly new stuff for nailgun 2.x.

2017-11-27 18:23 UTC, dwijnand requested changes
Please could you:

1. create an issue requesting this nailgun classes be released somewhere, and
2. add somewhere a reference to what commit sha these source files come from (for future reference)

2017-11-27 18:23 UTC, dwijnand commented on main-command/src/main/scala/sbt/internal/server/Server.scala
> +                case ConnectionType.Ssh => sys.error("ssh it not yet supported")
Hmm, maybe it's best to introduce this enum value when it's supported.

2017-11-28 03:14 UTC, eed3si9n commented
@dwijnand https://github.com/facebook/nailgun/pull/109

2017-11-28 06:12 UTC, dwijnand commented
Is there an issue about having a binary release on Maven Central?

2017-11-28 15:59 UTC, eed3si9n commented
> Is there an issue about having a binary release on Maven Central?

Binary release for Nailgun? 0.9.1 from 2012 is published, but there hasn't been public release yet since. The interesting bits that I am after were committed in 2017. It could mean that 0.9.2 is not yet out, or ppl are releasing in-house as app.

2017-11-28 16:03 UTC, dwijnand commented
> Binary release for Nailgun?

Either of nailgun or a subset of nailgun that includes the classes we're importing here.

I see you've created https://github.com/facebook/nailgun/issues/108#issuecomment-347390157 - I'd've preferred a standalone, more easily findable, issue, but I'm not going to make that get in the way of this landing.

2017-11-28 16:03 UTC, dwijnand approved these changes

2017-11-28 16:04 UTC, merged

2017-11-29 19:11 UTC, jameskoch2 commented
Is anyone looking at applying some of these same Sockets to ForkTests? That would have similar security benefits (though the subprocesses there are much more short-lived).

2017-11-29 20:58 UTC, eed3si9n commented
I think any inter-process communication is worth reviewing to see either Unix domain socket and/or server is applicable.

2018-02-11 12:22 UTC, jameskoch2 commented
I filed https://github.com/sbt/sbt/issues/3938 after closer inspection of the NamedPipes code, because by my reading it looks like it would still allow other users on the same machine to snoop on traffic.