Run scripted without sbt/launcher
sbt/sbt pull request #3920
Opened 2018-02-05 18:19 UTC by dwijnand

This runs the majority of sbt/sbt scripted tests without using sbt/launcher.

Still TODO:
* investigate the effects of changing the dependency between sbt and the scripted plugin

2018-02-05 22:41 UTC, eed3si9n requested changes

2018-02-05 22:41 UTC, eed3si9n commented on build.sbt
> +  .dependsOn(commandProj, sbtProj % "compile->test")
We should not use Test configuration since it's a mess to publish them to Maven Central.

2018-02-05 23:04 UTC, SethTisue commented
I just want to say this is cool and I'm glad it's happening.

2018-02-06 12:54 UTC, dwijnand commented
Given this is forking a new JVM to call RunFromSourceMain the compile-time dependency isn't totally necessary. I've re-written the setup to get the classpath required.

Still TODO:
* investigate the effects of changing this scripted behaviour WRT usage of scripted outside of sbt/sbt

2018-02-06 14:15 UTC, dwijnand commented
Also TODO:
* Evaluate the performance change of this change (i.e evaluate if it's even worth it.. ;.;)

2018-02-06 16:01 UTC, dwijnand commented
@eed3si9n this is green now and re-ready for review/evaluation.

2018-02-06 16:32 UTC, eed3si9n approved these changes

2018-02-06 16:33 UTC, merged