Fix race condition in non-forked, parallel tests.
sbt/sbt pull request #3985
Opened 2018-03-05 08:08 UTC by retronym

Non forked tests that are run in parallel groups can call into
a single instance of TestStatusReporter concurrently.

This seems to be limited to the startGroup/endGroup/testEvent
methods called in:

  https://github.com/sbt/sbt/blob/a41727fb17bb923036f90ca2ca62897def1a893e/testing/src/main/scala/sbt/TestFramework.scala#L100-L124

Which itself is called within:

  https://github.com/sbt/sbt/blob/a41727fb17bb923036f90ca2ca62897def1a893e/testing/src/main/scala/sbt/TestFramework.scala#L203-L229

Creating the `runnables` that are run in parallel (in builds so configured):

  https://github.com/sbt/sbt/blob/a6eb1260c8162bfbfcbfb8656f152854a93d33ae/main-actions/src/main/scala/sbt/Tests.scala#L222-L230

We believe this to be the cause of the hang witnessed in
the a suite of Scalacheck-framework tests in the Scala
build:

  https://github.com/scala/scala-jenkins-infra/issues/249

This commit uses a concurrent map to support concurrent
status updates.

2018-03-05 08:16 UTC, eed3si9n requested changes
Thanks!
A minor comment.

2018-03-05 08:16 UTC, eed3si9n commented on testing/src/main/scala/sbt/TestStatusReporter.scala
>      properties.asScala map { case (k, v) => (k, v.toLong) }
This line should be removed?

2018-03-05 08:23 UTC, retronym commented on testing/src/main/scala/sbt/TestStatusReporter.scala
>      properties.asScala map { case (k, v) => (k, v.toLong) }
yep, push-fed

2018-03-05 08:24 UTC, eed3si9n approved these changes

2018-03-06 11:45 UTC, dwijnand approved these changes
lgtm, but you need to tell MiMa to chillax on the `private[sbt]` changes:

```
[error]  * method write(scala.collection.mutable.Map,java.lang.String,java.io.File)Unit in object sbt.TestStatus's type is different in current version, where it is (scala.collection.Map,java.lang.String,java.io.File)Unit instead of (scala.collection.mutable.Map,java.lang.String,java.io.File)Unit
[error]    filter with: ProblemFilters.exclude[IncompatibleMethTypeProblem]("sbt.TestStatus.write")
[error]  * method read(java.io.File)scala.collection.mutable.Map in object sbt.TestStatus has a different result type in current version, where it is scala.collection.concurrent.Map rather than scala.collection.mutable.Map
[error]    filter with: ProblemFilters.exclude[IncompatibleResultTypeProblem]("sbt.TestStatus.read")
```

2018-03-07 21:19 UTC, eed3si9n commented
This is now merged as https://github.com/sbt/sbt/pull/3997

2018-03-07 21:19 UTC, closed without merging