Cleanup Resolve
sbt/sbt pull request #4044
Opened 2018-03-27 08:53 UTC by dwijnand

2018-03-27 14:12 UTC, eed3si9n requested changes
I am a bit confused with seemingly adhoc style changes in this PR. The point of having Scalafmt is so we don't have to do this.

2018-03-27 14:12 UTC, eed3si9n commented on main/src/main/scala/sbt/internal/Resolve.scala
> +      index: BuildUtil[_],
I don't know if this additional newline makes sense here.
Let Scalafmt be.

2018-03-27 14:12 UTC, eed3si9n commented on main/src/main/scala/sbt/internal/Resolve.scala
> +      scope: Scope,
Why...

2018-03-27 15:28 UTC, dwijnand commented
the default that Scalafmt has of aligning things on some random column instead of at tab stops makes the code illegible to me.

ideally I would change the configuration instead.

2018-03-27 15:34 UTC, eed3si9n commented
> the default that Scalafmt has of aligning things on some random column instead of at tab stops makes the code illegible to me.

Sure it's a bit odd, but I don't personally think "illegible."

> ideally I would change the configuration instead.

Let's not spend further dev time and Git history on whitespaces, at least until it really really becomes a problem. I think there are better/bigger fish we could fry.

2018-03-28 07:57 UTC, dwijnand commented
> I think there are better/bigger fish we could fry.

because you don't think it's illegible.

personally I do this again and again while tackling the codebase and often throw it away (or leave it my workspace dirty, or throw it in a unpublished branch). it's tiresome.

2018-03-28 12:36 UTC, eed3si9n commented
Let's seek a general solution to this. Wouldn't everything be solved if we increased the `maxColumn = 100` to some large number and/or set align.openParenCallSite to false?

2018-03-28 14:28 UTC, dwijnand commented
> Let's seek a general solution to this.

happy to

> Wouldn't everything be solved if we increased the maxColumn = 100 to some large number and/or set align.openParenCallSite to false?

yeah `align.openParenCallSite = false` and `align.openParenDefnSite = false` (https://github.com/dwijnand/sbt/commit/992f6251e8642abf33e860e0bf8ac0abc55880b0) definitely help.

I'll try a few ways and come back.

2018-04-04 14:39 UTC, dwijnand commented
now builds on #4064

2018-04-24 21:18 UTC, merged