add human readable total time
sbt/sbt pull request #4278
Opened 2018-07-21 16:14 UTC by jozic

- [X] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/1.x/CONTRIBUTING.md) guidelines

Not sure this requires change.md file, but let me know if it's needed

**Motivation:**
 for big multimodule projects sbt often report `Total time: 123456 s, ...`
Which is not human friendly. So this PR adds some human friendly duration. Please see spec for examples

2018-07-21 18:46 UTC, eed3si9n requested changes
overall looks good, but I think the new file needs a header.

Could you generate headers using `headerCreate`?

2018-07-21 19:57 UTC, jozic commented
@eed3si9n not sure why, but `headerCreate and `headerCheck` do nothing
I've added the header manually, hopefully it's okay

2018-07-21 23:05 UTC, eed3si9n approved these changes
LGTM

2018-07-23 19:31 UTC, jozic commented
looks like travis-ci failure is unrelated `Error: Could not retrieve sbt 1.1.6: missing sbt.xMain`
@eed3si9n do I need to do anything else here? thanks

2018-07-29 17:56 UTC, merged

2018-07-30 05:46 UTC, jozic commented
thanks!