Build time configurable library management
sbt/sbt pull request #4398
Opened 2018-10-03 07:55 UTC by andreaTP

- [X] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

This is a pre-requisite to automate integration tests for alternative implementations of `librarymanagement` as discussed in the Gitter channel with @eed3si9n and @leonardehrenfried

2018-10-08 11:32 UTC, andreaTP commented
ping for a review, this should be easy.

2018-10-09 03:44 UTC, eed3si9n requested changes
Some minor comments.
Thanks for pushing this forward.

2018-10-09 03:44 UTC, eed3si9n commented on project/Dependencies.scala
> +    sys.props.get("sbt.librarymanagement.version") match {
I recently added build-time flag for fatal warnings and I used `sbt.build` prefix.
Could we rename this to `sbt.build.lm.version`?

2018-10-09 03:44 UTC, eed3si9n commented on project/Dependencies.scala
> +      sys.props.get("sbt.librarymanagement.groupID") match {
`groupID` is a Maven term. My preference is `sbt.build.lm.organization`.

2018-10-09 03:44 UTC, eed3si9n commented on project/Dependencies.scala
> +      sys.props.get("sbt.librarymanagement.artifactID") match {
Similarly `sbt.build.lm.moduleName`.

2018-10-09 08:06 UTC, andreaTP commented
Done all requested renamings, squashed and rebased on latest develop.

2018-10-10 13:53 UTC, eed3si9n approved these changes
LGTM pending CI

2018-10-12 00:21 UTC, merged