Glob performance
sbt/sbt pull request #4539
Opened 2019-02-03 00:29 UTC by eatkins

- [x] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

This PR is built on top of #4535, #4537 and https://github.com/sbt/io/pull/216. I will update the PR as those other PRs are merged and a new io version is released.

High level, this replaces a number of file apis within sbt with glob based apis. This is good for performance because the glob based file look ups are generally routed through the file system cache. Even when the cache is not used, the performance should be good because of optimizations that I made in swoval for recursively listing a directory. Another benefit is that in watch, I can swap out the global file tree repository to determine which globs are actually used by a task. This enables watch to work even when the watch sources are unspecified or hidden from the dependency graph in a dynamic task.

I also actually implemented #3678, which allows clean to be scoped to the compile task and Compile / Test configurations. I copied some of the scripted tests from that #3678 and added a few additional scripted tests.

2019-02-04 15:30 UTC, eed3si9n requested changes

2019-02-04 15:30 UTC, eed3si9n commented on sbt/src/sbt-test/actions/compile-clean/test
> +> test:compile::clean
I think this should be `Test/clean`. In other words, `clean` should just be scoped to `Test` configuration.

2019-02-04 20:20 UTC, eatkins commented on sbt/src/sbt-test/actions/compile-clean/test
> +> test:compile::clean
FWIW, I copied this test exactly from #3678. I think there is a valid use case for scoping both to the configuration and to the task separately. I might want to clear out the output files for just a specific task in a configuration but when i clean the configuration, I want to clear out the output files for all tasks in the configuration. Does that make sense? I don't mind dropping the task specific clean, but that was the motivation.

2019-02-05 04:11 UTC, eatkins commented
Sigh, windows is proving annoying wrt the clean task. Hopefully I'll have everything working by tomorrow afternoon.

2019-02-07 04:41 UTC, eatkins commented
It turns out that the java watchservice for windows is not ideal for the sbt use case. It reports way too many events. For example, if you open a file, an event is created. I need to add a native windows watch service (similar to the one i wrote for macos) that filters watch events to swoval. This shouldn't be too hard because the two apis are similar (inotify is completely different). Also, I already have the test suite written.

2019-02-08 01:00 UTC, eatkins commented
Yeah, there was a nasty performance bug in swoval: https://github.com/sbt/io/pull/222

2019-03-22 06:39 UTC, eatkins commented
I turned off the cache in this PR. I'll make it configurable, but not default, in #4512.

2019-03-22 14:46 UTC, eed3si9n commented
@eatkins Does this work for you locally?

```
[error] x source-dependencies/relative-source-error 
[error]  Cause of test exception: {line 3}  Command succeeded but failure was expected
```

2019-03-22 14:54 UTC, eed3si9n commented on sbt/src/sbt-test/actions/compile-clean/test
> +> test:compile::clean
I think task scoping here is confusing since all sorts of tasks can trigger a compilation, including `test`.

2019-03-22 14:57 UTC, eatkins commented
https://github.com/sbt/sbt/pull/4539/commits/ffa69ea5d690b5d8d548e0eefd98e83587a30de2

The commit message is arguably a little bit glib. Relative source directories are a bit tricky since sbt doesn't have a notion of current working directory so relative sources are implicitly relative to the sbt base directory. I guess marking the test PENDING is an option rather than deleting it, but it's not straightforward to make the previous semantics work with the new version of the swoval library (which automatically converts non relative paths to absolute paths internally at interface boundaries).

2019-03-22 15:13 UTC, eatkins commented on sbt/src/sbt-test/actions/compile-clean/test
> +> test:compile::clean
To play devil's advocate, what if I just want to remove the jars generated by `package`? What if I want to remove the class files but not the jars? For me, it's more confusing if clean cannot be scoped at the task level. Most users are just going to use clean at the config level but I don't see why we need to exclude it at the task level.

2019-03-22 15:16 UTC, eed3si9n commented on sbt/src/sbt-test/actions/compile-clean/test
> +> test:compile::clean
One of the reasons is that I think task-scoped tasks are confusing concepts to users, and I want to avoid it as much as possible.

2019-03-22 15:18 UTC, eed3si9n commented
As long as https://github.com/sbt/sbt/issues/923 remains fixed, we should be ok.

2019-03-22 15:22 UTC, eatkins commented on sbt/src/sbt-test/actions/compile-clean/test
> +> test:compile::clean
I get that, but the task scoped task is only relevant for advanced users who even know that syntax. As is, the config scoped clean works as expected and most users would never even think to try the task scoped version. Personally I think the real problem is the legacy `:` based syntax. When using the slash syntax, I don't think it's that confusing. Would it bother you less if the test was written `Test/compile/clean`? That works.

2019-03-22 15:24 UTC, eatkins commented on sbt/src/sbt-test/actions/compile-clean/test
> +> test:compile::clean
Oh, ugh. I see what you're saying a bit more now. Compile is really a special case because of the default configurations.

2019-03-22 15:51 UTC, eed3si9n commented on sbt/src/sbt-test/actions/compile-clean/test
> +> test:compile::clean
When I type `clean`, what I often want is "clear the caching behavior and start from scratch", which doesn't necessarily have to do with wiping out the `target/` directory. Having that work for one task is tricky, let alone making sure it works consistently for all tasks transitively. Config-scoped clean deleting `classes/` is much more low-tech, but addresses a use case in a consistent way.

2019-03-22 15:57 UTC, eatkins commented on sbt/src/sbt-test/actions/compile-clean/test
> +> test:compile::clean
I disagree but I don't care enough to continue the debate so I'll just make it work for just the configuration.

2019-03-22 16:33 UTC, eatkins commented on sbt/src/sbt-test/actions/compile-clean/test
> +> test:compile::clean
https://github.com/sbt/sbt/compare/2da32eccd6f3e242d2859fa546d76f805b55a17d..f26afe6681da174e80e2ca6db8e638e1abf732cc

2019-03-22 16:36 UTC, eed3si9n approved these changes
LGTM pending Travis

2019-03-22 17:34 UTC, merged