Disable automatic scalafmt
sbt/sbt pull request #4586
Opened 2019-03-28 03:58 UTC by eatkins

This is unbearably slow.

- [ ] I've read the [CONTRIBUTING](https://github.com/sbt/sbt/blob/develop/CONTRIBUTING.md) guidelines

2019-03-28 04:06 UTC, eed3si9n requested changes

2019-03-28 04:06 UTC, eed3si9n commented on build.sbt
> +      scalafmtOnCompile := false,
Could you update CONTRIBUTING and maybe even the `onLoadMessage` to tell ppl to run mima check and Scalafmt commands before committing?

2019-03-28 04:34 UTC, eatkins commented
Oh, yes. That makes sense, we should also add the scalafmt check to travis as @xuwei-k suggested.

2019-04-18 07:49 UTC, dwijnand commented
You could give sbt-scalafmt 2.0.0 a try.  It includes performance improvements: https://github.com/scalameta/sbt-scalafmt/releases/tag/v2.0.0, both in using zinc's analysis to make scalafmt incremental and caching of the Scalafmt object.

2019-04-20 07:33 UTC, eed3si9n commented
closing in favor of https://github.com/sbt/sbt/pull/4623

2019-04-20 07:33 UTC, closed without merging