Close classloaders
sbt/sbt pull request #4786
Opened 2019-06-08 21:36 UTC by eatkins

2019-06-08 21:38 UTC, eatkins commented
This is in response to #4784.

2019-06-08 23:00 UTC, eed3si9n requested changes

2019-06-08 23:00 UTC, eed3si9n commented on main/src/main/scala/sbt/internal/SysProp.scala
> +  def closeClassLoaders: Boolean = getOrTrue("sbt.close.classloaders")
I'd make this `sbt.classloader.close`.

2019-06-08 23:16 UTC, eed3si9n commented on main/src/main/scala/sbt/internal/SysProp.scala
> +  def closeClassLoaders: Boolean = getOrTrue("sbt.close.classloaders")
https://github.com/sbt/sbt/pull/4787

2019-06-09 00:08 UTC, eatkins commented on main/src/main/scala/sbt/internal/SysProp.scala
> +  def closeClassLoaders: Boolean = getOrTrue("sbt.close.classloaders")
Done.

2019-06-09 00:32 UTC, eed3si9n approved these changes

2019-06-09 00:52 UTC, merged