Don't use Set[Incomplete]
sbt/sbt pull request #4806
Opened 2019-06-13 01:11 UTC by eatkins

It's very expensive to compute the hash code of a deeply nested
Incomplete. To prevent a loop, we only want to check for object equality
anyway, which System.identityHashCode gives us (to reasonable
approximation).

2019-06-13 01:13 UTC, nafg commented
Perhaps it would be more elegant to use `java.util.IdentityHashMap`

2019-06-13 01:15 UTC, nafg commented
Something like `java.util.Collections.newSetFromMap(new java.util.IdentityHashMap).asScala` using JavaConverters

2019-06-13 01:29 UTC, eatkins commented
That's a good idea.

2019-06-13 23:30 UTC, eed3si9n requested changes

2019-06-13 23:30 UTC, eed3si9n commented on main/src/main/scala/sbt/internal/Aggregation.scala
> +    lazy val visited = Collections
I think it should be noted here in comments that we tried using Set and it caused performance issue due to deeply nested case class doing a fairly straightforward operation.

2019-06-14 07:10 UTC, eed3si9n approved these changes

2019-06-14 07:10 UTC, merged