Add scripted test for symlink source monitoring
sbt/sbt pull request #4899
Opened 2019-07-26 17:10 UTC by eatkins

The swoval library automatically watches the _target_ of symlinks. I had
been meaning to add a scripted test to ensure that in sbt continuous
builds detect changes to the target of symlinks. The naive approach of
just watching all of the files in the source directory doesn't work
because the native watch process will just watch the symlink node itself
and not detect updates to its target. This test would have thus failed
with 1.2.8.

2019-07-26 17:53 UTC, eed3si9n commented
```
Running watch/symlinks
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received
```

2019-07-26 17:54 UTC, eatkins commented
Yeah. I was relying on a directory that was present on my file system because git doesn't store empty directories.

2019-07-26 18:49 UTC, eatkins commented
It turns out that watching the targets of symlinked files doesn't work on windows. This is a bit strange because I have tests for this in the swoval library. For now, I'm just going to skip the tests for monitoring the targets of symlinked files on windows. The tests that we correctly monitor the target files with symlinked directories still work on all platforms.

2019-07-29 20:06 UTC, eed3si9n requested changes
Since AppVeyor didn't post, I'll link this as a reminder - https://ci.appveyor.com/project/sbt/sbt/builds/26273400

2019-07-30 03:31 UTC, eatkins commented
appveyor is passing now.

2019-07-30 21:39 UTC, eed3si9n approved these changes

2019-07-30 21:39 UTC, merged