bsp: Implementing `buildTarget/cleanCache`
sbt/sbt pull request #6638
Opened 2021-08-27 07:05 UTC by hmemcpy

Fixes #6569

This command is invoked by IntelliJ whenever a Rebuild operation is called. Unfortunately, because it's not implemented, this causes bsp-imported projects in IntelliJ to hang when asking to rebuild.

It works fine in bloop-imported projects because bloop implements this API.

2021-08-27 07:05 UTC, lightbend-cla-validator commented
Hi @hmemcpy,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[https://www.lightbend.com/contribute/cla](https://www.lightbend.com/contribute/cla)

2021-08-27 07:13 UTC, hmemcpy commented
@adpi2 hello, sorry for the ping. Unfortunately, this isn't actually working, and I really have no idea why :(
The test passes, but when I actually try to test this in a local test project, when I call `cleanCache` from IntelliJ (or even send the json payload via `sbt -bsp`) I immediately get a `shutdown`.

I really don't know what I'm missing... any tips appreciated!

2021-08-27 07:56 UTC, hmemcpy commented
Update! I got it working... somehow. I made sure to clean everything up, do a `publishLocal`, followed by a `"reboot dev"` in my test project... and voilla!
Will finalize the PR soon.
![image](https://user-images.githubusercontent.com/601206/131094697-aaae0903-2d0b-48ab-8f42-ed5cbbdda207.png)

2021-08-27 08:07 UTC, hmemcpy commented on main/src/main/scala/sbt/internal/server/BuildServerProtocol.scala
> +        val statusCodes = Keys.bspBuildTarget.result.all(filter).value
I'm not sure about this one... do I need to add my own item?

2021-08-27 08:10 UTC, adpi2 commented
@hmemcpy Thanks for pinging me! It is great that you are working on it.

I tested it locally and it seems to work. Make sure you clean the `.sbt` cache after running `publishLocal` with:
```
rm -Rf ~/.sbt/boot/scala-2.12.14/org.scala-sbt/sbt/1.5.5-SNAPSHOT
```
Otherwise the launcher loads the old cached jars rather than the new ones.

Another way to test the `buildTarget/cleanCache` request is to add a test in [BuildServerTest](https://github.com/sbt/sbt/blob/develop/server-test/src/test/scala/testpkg/BuildServerTest.scala).

You can run it with:
```scala
sbt:sbt> serverTestProj/testOnly testpkg.BuildServerTest
```

2021-08-27 08:14 UTC, adpi2 commented on main/src/main/scala/sbt/internal/server/BuildServerProtocol.scala
> +        val statusCodes = Keys.bspBuildTarget.result.all(filter).value
I don't think you need an item here. You may be able to use `clean` directly:

```scala
Keys.clean.result.all(filter).value
```

2021-08-27 08:44 UTC, hmemcpy commented
@adpi2 I guess initially I had old jars in the cache. I'll test this a bit more and will mark the PR as done. Thanks again for the help!

2021-08-27 10:18 UTC, hmemcpy commented
And it's good to go!

2021-08-27 12:32 UTC, adpi2 requested changes
Thanks @hmemcpy!

Most of the comments are suggestions. But I think it is important to check in the test that `buildTarget/cleanCache` empties the class directory.

2021-08-27 12:32 UTC, adpi2 commented on main/src/main/scala/sbt/internal/server/BuildServerProtocol.scala
> +        val statusCodes = Keys.clean.result.all(filter).value
I think `result` is a better name than `statusCodes` because `statusCodes` generally means there is an `Int` somewhere describing the output of the task. But here the type is `Seq[Result[Unit]]`.

```suggestion
        val results = Keys.clean.result.all(filter).value
```

2021-08-27 12:32 UTC, adpi2 commented on main/src/main/scala/sbt/internal/server/BuildServerProtocol.scala
> +        }
The protocol is not really clear but I don't think we should throw an exception if only one build target fails. So I suggest this instead.

```scala
      val result = anyOrThrow(statusCodes).size == targets.size
```

If all the targets fail we throw an exception otherwise we check that the number of successful targets is equal to the number of targets in the request.

If `result` is false, that means there is at least one target that failed. If it is true everything is okay.

2021-08-27 12:32 UTC, adpi2 commented on server-test/src/test/scala/testpkg/BuildServerTest.scala
> +      s"""{ "jsonrpc": "2.0", "id": "32", "method": "buildTarget/cleanCache", "params": {
Not a big deal but every request should have a unique id. Here `32` is already used by the `buildTarget/compile` request.

```suggestion
      s"""{ "jsonrpc": "2.0", "id": "44", "method": "buildTarget/cleanCache", "params": {
```

2021-08-27 12:32 UTC, adpi2 commented on server-test/src/test/scala/testpkg/BuildServerTest.scala
> +    assert(res.cleaned)
Would it be possible to check that the class directory was not empty before the request? And that it is empty after the request?

2021-08-27 12:32 UTC, adpi2 commented on main/src/main/scala/sbt/internal/server/BuildServerProtocol.scala
> +      workspace.warnIfBuildsNonEmpty(Method.Compile, s.log)
```suggestion
      workspace.warnIfBuildsNonEmpty(Method.CleanCache, s.log)
```

2021-08-27 12:35 UTC, hmemcpy commented
Thanks for the comments! My copy-pasting was obvious here :)
I'll make the changes and will figure out how to check for empty directories!

2021-08-27 14:03 UTC, hmemcpy commented on server-test/src/test/scala/testpkg/BuildServerTest.scala
> +    assert(res.cleaned)
@adpi2 Done, but I am hoping there's a less... hacky way of checking these files. I don't think I saw anything in the bsp protocol to let me list the target directories...

2021-08-27 15:29 UTC, adpi2 commented on server-test/src/test/scala/testpkg/BuildServerTest.scala
> +    assert(res.cleaned)
I cannot think of anything better than it is already :)

2021-08-27 15:29 UTC, adpi2 submitted a review, later dismissed
LGTM

2021-08-28 08:32 UTC, hmemcpy commented
Oops, temporarily marking this as draft. It looks like the `results.size == targets.size` isn't a good check. I just noticed that out of the 3 targets, I get only 2 results back. The sent targets are:

```
  "targets": [
    {
      "uri": "file:/Users/hmemcpy/git/sbt-playground/#root-build"
    },
    {
      "uri": "file:/Users/hmemcpy/git/sbt-playground/#root/Compile"
    },
    {
      "uri": "file:/Users/hmemcpy/git/sbt-playground/#root/Test"
    }
```
 
And I get back just two. Unfortunately I don't know what they are, since it's a Unit result. Is, perhaps, `root-build` not a "real" target?

Do you have a better suggestion for doing the check? If not, perhaps I can revert it back to the `allOrThrow` logic from before?

2021-08-28 10:53 UTC, hmemcpy commented
Alright... I managed to implement a solution for both "Rebuild Project" (which includes the root build), as well as a regular "Rebuild module" (which includes the exact targets to rebuild).

Would love any suggestions to improve this!

2021-09-06 08:36 UTC, adpi2 approved these changes
I don't see any obvious way to clean the build.sbt target. So this solution seems ok to me.

2021-09-06 10:25 UTC, merged

2021-09-06 10:26 UTC, hmemcpy commented
TYVM! :)