[2.x] Replace tuple with proper record type for licenses
sbt/sbt pull request #7753
Opened 2024-10-11 14:45 UTC by adpi2

This is a merge of https://github.com/sbt/librarymanagement/pull/382, originally by @mdedetrich

@mdedetrich more changes are needed in the the sbt part to make it compile. If you can finish the work, that would be great.

2024-10-14 09:31 UTC, mdedetrich commented
Thanks looking into it now

2024-10-18 09:49 UTC, mdedetrich commented
@adpi2 I am trying to fix this but I don't have access to your branch to add commits

2024-10-18 09:56 UTC, adpi2 commented
Sorry for that. Could you pish to your fork and create another PR then?

2024-10-18 09:57 UTC, mdedetrich commented
Sure will do

2024-10-18 10:05 UTC, mdedetrich commented
Pull request is here https://github.com/adpi2/sbt/pull/36

2024-10-18 12:31 UTC, mdedetrich commented
@adpi2 This should fix the latest scripted test https://github.com/adpi2/sbt/pull/37

2024-10-18 13:47 UTC, mdedetrich commented
@adpi2 Fix for the latest CI run https://github.com/adpi2/sbt/pull/38 

Sorry that this is so iterative, I am currently have issues loading the sbt project properly on my machine right now so relying a bit on CI

2024-10-18 14:24 UTC, mdedetrich commented
@adpi2 And again, https://github.com/adpi2/sbt/pull/39. Really hope that this is the last one...

2024-10-21 08:19 UTC, mdedetrich commented
@adpi2 Everything passes now!

2024-10-22 13:54 UTC, eed3si9n requested changes

2024-10-22 13:54 UTC, eed3si9n commented on main/src/main/scala/sbt/Keys.scala
> +  val licenses = settingKey[Seq[LicenseInfo]]("Project licenses.").withRank(BMinusSetting)
While I'm +1 in principle, we should try to make the transition as smooth as possible to minimize the disruption cost. For example we should consider introducing a givens converter so sbt 1.x tuple would work out of box, and maybe show a warning.

2024-10-22 13:54 UTC, eed3si9n commented on sbt-app/src/sbt-test/dependency-management/cache-update/build.sbt
> +      licenses := Seq(LicenseInfo("Apache 2", uri("http://www.apache.org/licenses/LICENSE-2.0.txt"), None, None)),
`None, None` here is not nice. Could you add since tag to produce apply with two fields plz?

2024-10-22 13:54 UTC, eed3si9n commented on lm-core/src/main/contraband/librarymanagement.json
> +      "name": "LicenseInfo",
This probably should be called License. Note that we already have License object that lists popular licenses. We should let the companion object expand License Extra so we don't lose that.

2024-12-05 06:05 UTC, eed3si9n commented
I have another PR here - https://github.com/sbt/sbt/pull/7927

2024-12-06 15:48 UTC, closed without merging