fix: concurrency control around Scala 3 compiler
sbt/sbt pull request #7938
Opened 2024-12-10 04:27 UTC by eed3si9n

## Problem
Early initialization thread throws ConcurrentModificationException.

## Solution
This puts in synchronized to lock for the access.

2024-12-10 09:06 UTC, adpi2 requested changes
I don't think this fixes the concurrency issue.

Looking at the stack trace, it seems that dotty is iterating the `System.properties` while another thread modifies them. Could it be that sbt, or a plugin modifies the `System.properties`?

2024-12-10 09:06 UTC, adpi2 commented on buildfile/src/main/scala/sbt/internal/parser/SbtParser.scala
> +    defaultGlobalForParser
Object initialization is already thread-safe, so I don’t think these changes are actually fixing anything. Or am I missing something?

2024-12-10 09:20 UTC, eed3si9n commented
https://eed3si9n.com/december-adventure-2024/ has commentary on the whereabout of the thread.

2024-12-10 09:25 UTC, eed3si9n commented on buildfile/src/main/scala/sbt/internal/parser/SbtParser.scala
> +    defaultGlobalForParser
defaultGlobalForParser is accessed by three places, including a thread we start as a background JIT warmup. I'm wrapping the access to synchronized so we don't give access to this variable concurrently.

2024-12-10 10:03 UTC, adpi2 commented on buildfile/src/main/scala/sbt/internal/parser/SbtParser.scala
> +    defaultGlobalForParser
Its initialization and access is already thread safe.

Really I don't think the problem is here. It's rather that the `ParserDriver.<init>` which is called only once iterate over the `System.properties` while another thread is mutating those properties.

2024-12-10 10:20 UTC, jtjeferreira commented on buildfile/src/main/scala/sbt/internal/parser/SbtParser.scala
> +    defaultGlobalForParser
`java.util.Properties` is [supposedly](https://docs.oracle.com/javase/8/docs/api/java/util/Properties.html) thread safe...
>  This class is thread-safe: multiple threads can share a single Properties object without the need for external synchronization

2024-12-10 10:24 UTC, eed3si9n commented on buildfile/src/main/scala/sbt/internal/parser/SbtParser.scala
> +    defaultGlobalForParser
We do 

sys.props.put("jna.nosys", "true")

in Main.scala and there might be more by users potentially. so maybe it's not safe to change and read at the same time?

2024-12-10 10:59 UTC, jtjeferreira commented on buildfile/src/main/scala/sbt/internal/parser/SbtParser.scala
> +    defaultGlobalForParser
Also [dotty.tools.dotc.config.WrappedProperties#systemProperties](https://github.com/scala/scala3/blob/1775d0be938fe78126600502f3c3c2e6d0429f9e/compiler/src/dotty/tools/dotc/config/WrappedProperties.scala#L24-L27) uses `System.getProperties.asScala.iterator` and maybe it should just use `System.getProperties.asScala`

Also `dotty.tools.dotc.config.PathResolver.Environment.javaBootClassPath` is `def javaBootClassPath: String = propOrElse("sun.boot.class.path", searchForBootClasspath)` and the 2nd argument is always evaluated.

But these are bugs for the scala repo...

2024-12-10 11:12 UTC, jtjeferreira commented on buildfile/src/main/scala/sbt/internal/parser/SbtParser.scala
> +    defaultGlobalForParser
And after some archeology: https://github.com/scala/scala/commit/f6859f28bb49193fde83e6020a6a89ce926a91e8

I will try to backport that commit to scala 3

2024-12-10 12:37 UTC, eed3si9n commented on buildfile/src/main/scala/sbt/internal/parser/SbtParser.scala
> +    defaultGlobalForParser
Added fdb7ca23841cf4db91545a206509542e12e65862 to wrap in `Retry(...)` instead.

2024-12-10 13:00 UTC, adpi2 approved these changes
LGTM

2024-12-10 13:17 UTC, eed3si9n commented on buildfile/src/main/scala/sbt/internal/parser/SbtParser.scala
> +    defaultGlobalForParser
Thanks both for the review / detective work!

2024-12-10 13:30 UTC, merged

2024-12-19 23:13 UTC, jtjeferreira commented on buildfile/src/main/scala/sbt/internal/parser/SbtParser.scala
> +    Retry(ParseDriver())
this Retry did not work because it just retries `IOException`...